### ISSUE TITLE
is this ratted 

### ISSUE THREAD

**Issue by SyuyMax** [shxp3/CrossSine#11]
![Bild_2024-04-04_115617480](https://github.com/shxp3/CrossSine/assets/155258333/f8cd4178-72b3-4b23-b09f-4225809bfa6b)
some pp say it is

**Comment by larryngton** [comment]
it rat trast 100% rial

**Comment by SyuyMax** [comment]
yes



________________________________
Von: lucas ***@***.***>
Gesendet: Thursday, April 4, 2024 3:52:54 PM
An: shxp3/CrossSine ***@***.***>
Cc: Max ***@***.***>; Author ***@***.***>
Betreff: Re: [shxp3/CrossSine] is this ratted (Issue #11)


it rat trast 100% rial

**Comment by Reycko** [comment]
This repo's the official source, if you don'ttrust it then just compile it urself
