### ISSUE TITLE
bitcoin miner

### ISSUE THREAD

**Issue by DoubleRainbowXT** [shxp3/CrossSine#6]
This is definitly a bitcoin miner or a rat, let me explain.

On any minecraft version i get atleast 60 fps on 1.8.9 i get 398 fps sometimes with highest options, so i downloaded the client with optifine and ran it.
My pc was heating up rapidly and i got 10 fps max with 1 chunk and lowest possible optifine settings.

Dont download it unless you got nasa pc for this faggot to bitcoin mine on.

**Comment by thisisverycool** [comment]
lmao

**Comment by intexpression** [comment]
this is called a shit optimization not a bitcoin miner 😭😭

**Comment by crave6948** [comment]
I didn't work on this project at all, so I don't know if it exists or not.
